name: Deploy Static Files

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Configure SSH for ProxyJump
      run: |
        echo -e "Host proxy-securot\n  HostName app.securot.com\n  User yury\n" >> ~/.ssh/config
        echo -e "Host devmvp.securot.net\n  HostName devmvp\n  User git\n  ProxyJump yury@app.securot.com\n" >> ~/.ssh/config

    - name: Sync files to server
      run: |
        rsync -avz --delete ./staticfiles/ git@devmvp:/usr/share/securotserver/test/

